### ISSUE TITLE
Environment detection for javascript

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-web-pdf#132]
I have an Asciidoc file which has significant javascript in it.

When it opens, I detect whether there is a URL fragment e.g. `url#some_id` and if there is I take particular actions via javascript (mainly to show all items in the document so they can be deep linked).

By default however some sections are hidden. This is great for HTML because I have an interface which allows interaction with the document (a basic issue selection across a few categories), however for producing a PDF this is undesirable.

Similar to having a backend to indicate pdf is being made within the Asciidoc format (see #129), it would be useful (and maybe it's already there and I'm just not aware) a DOM property that can be checked to determine if the html has been loaded in Puppeteer and take specific action (i.e. backend detection for javascript).  

Probably there is already a way to do this by detecting if paged.js is loaded for example (any suggestions?) but a standardised interface might be a good idea (or just helpful for me :smile_cat:).

**Comment by danyill** [comment]
There is very likely a better, more reliable approach but I'm using: `window.Paged !== undefined` to detect paged.js at the moment.

**Comment by Mogztter** [comment]
We could probably add a meta in the header:

```html
<meta name="generator" content="Asciidoctor Web PDF 1.0.0-alpha.4"/>
```

What do you think?

**Comment by ahus1** [comment]
As long as you choose something that's part of HTML, it will be dependent on the template. The default template has `window.Paged`, it also has `window.AsciidoctorPDF`. Other templates don't. The same will be true for a meta tag.

To detect if something is rendered for a PDF you're better off using an attribute as described in #129 and use it to conditionally include the JavaScript, or to pass the attribute on to the document specific JavaScript you choose to include.

**Comment by Mogztter** [comment]
I agree with @ahus1 
Still I think it can be useful to add the generator 😅

**Comment by danyill** [comment]
Fair enough @ahus1, thanks for your thoughts :+1:. I'm happy to close this but I'll leave it up to yourself or @Mogztter

**Comment by Mogztter** [comment]
Closing, I will open a new issue for adding the generator metadata in the `<head>`.
