### ISSUE TITLE
Support docinfo files

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-web-pdf#147]
I think currently [docinfo files](https://asciidoctor.org/docs/user-manual/#docinfo-file) are not supported (at least my testing show they are not included in the html output).

This would be useful to allow the end-user to readily augment the default stylesheet.

**Comment by Mogztter** [comment]
That's true and we should support docinfo files but if you want to augment the default stylesheet you should probably use the `stylesheet` attribute with multiple values separated by semicolons: https://github.com/Mogztter/asciidoctor-pdf.js/issues/103

**Comment by Mogztter** [comment]
See https://github.com/Mogztter/asciidoctor-pdf.js/issues/104#issue-517917170 for an example.
