### ISSUE TITLE
Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by rohel01** [Mogztter/asciidoctor-web-pdf#206]
Hello,

I am trying to generate rather large document (~70 pages with diagrams).
All my assets are on my local harddrive. 

I get the following error:

> Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded

Is there a way to increase this this timeout value ?

My versions

> Asciidoctor PDF 1.0.0-alpha.7 using Asciidoctor.js 2.1.1 (Asciidoctor 2.0.10) [https://asciidoctor.org]
> Runtime Environment (node v12.16.1 on linux)
> CLI version 3.2.0

Kind regards,

**Comment by Mogztter** [comment]
> Is there a way to increase this this timeout value ?

No we are using the default value from Puppeteer but it should be fairly simple to implement: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagegotourl-options

I think we should use a environment variable. Regarding the name it's tricky because we could use a specific name like `PUPPETEER_GOTO_TIMEOUT` but it tells a lot about the internal and it might be confusing for users... so we might use `CONVERT_TIMEOUT` or just `TIMEOUT`?
I guess it might be fine if we catch the exception and use an explicit error message:

```
Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded
TIP: You can increase the default timeout using the environment variable PUPPETEER_GOTO_TIMEOUT
```

For reference, it's also possible to get a timeout exception when we launch Chrome: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions

**Comment by Mogztter** [comment]
> I am trying to generate rather large document (~70 pages with diagrams).
All my assets are on my local harddrive.
I get the following error:
Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded

Having said that, 30 seconds to navigate to a page is still really long. Did you try to open the page is a non-headless browser using `--preview`? Maybe you will find out why the page takes so long to load.

**Comment by butcherpete** [comment]
I am having the same issue.

I am trying to generate a PDF from a "book" file; the  ADOC file specifies toc levels and points to multiple (9) include files:  ie. `include::overview-elements.adoc[]`

````
Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded
````

Asciidoctor PDF 1.0.0-alpha.7 using Asciidoctor.js 2.1.1 (Asciidoctor 2.0.10) [https://asciidoctor.org]
Runtime Environment (node v13.13.0 on darwin)
CLI version 3.2.0

**Comment by Mogztter** [comment]
Also if it's not confidential, you can send me your document (privately) so I can run a few tests.

**Comment by butcherpete** [comment]
It appeared that Puppeteer? gets caught in a loop and kept adding pages repeatedly. The doc itself is only 39 pages long, but in --preview mode I viewed it growing to over 2500 pages.

I think the issue was that I had created a code-block using five instead of four hyphens. Thanks.

**Comment by Mogztter** [comment]
> It appeared that Puppeteer? gets caught in a loop and kept adding pages repeatedly. The doc itself is only 39 pages long, but in --preview mode I viewed it growing to over 2500 pages.

It's most likely a bug/limitation in Paged.js, we've seen this issue before. Sometimes Paged.js cannot figure out how to fit an element into the page and then the loop begins.

> I think the issue was that I had created a code-block using five instead of four hyphens. Thanks.

Did it solve your timeout issue?

**Comment by rohel01** [comment]
> > I am trying to generate rather large document (~70 pages with diagrams).
> > All my assets are on my local harddrive.
> > I get the following error:
> > Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded
> 
> Having said that, 30 seconds to navigate to a page is still really long. Did you try to open the page is a non-headless browser using `--preview`? Maybe you will find out why the page takes so long to load.

I will try. My document does contain some peculiar stuff, for which I just opened an [issue](https://github.com/asciidoctor/asciidoctor-pdf/issues/1655) on asciidoctor-pdf...  Compiling this sample triggers the timeout error from asciidoctor-pdf.js.
Here it is, if you are interested:

[sample.txt](https://github.com/Mogztter/asciidoctor-pdf.js/files/4511229/sample.txt)

**Comment by rohel01** [comment]
Hello, 

I confirm that manually solving the multipage table cell layout by hand removed the Navigation timout.
Now, I have an other timeout:

> Unable to generate the PDF - Error: TimeoutError: waiting for function failed: timeout 30000ms exceeded

If I open the page is a non-headless browser using `--preview`, I see the html being paged, but the Navigation timeout comes back.

> Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded
> Preview mode entered, needs to be manually terminated using Ctrl+C!
