### ISSUE TITLE
Bug in counter() and string-set

### ISSUE THREAD

**Issue by henriette-einstein** [Mogztter/asciidoctor-web-pdf#255]
I created a simple print CSS to test the counter() functionality. It works fine with the Prince formatter, but has issues with asciidoctor-web-pdf.

1. The counter() function does not work as expected
2. The string-set directive leads to an exception

The output of the exception is pasted here:

<img width="903" alt="Bildschirmfoto 2020-06-08 um 14 10 12" src="https://user-images.githubusercontent.com/45788168/84030307-20470280-a994-11ea-8104-19910011a0c0.png">

I created a pull request for the problematic files which also includes the output PDF of the Prince formatter.

If you comment out line 97 of print.css, the exception will disappear.

**Comment by henriette-einstein** [comment]
I am using the following version on a Mac

````
Asciidoctor PDF 1.0.0-alpha.7 using Asciidoctor.js 2.2.0 (Asciidoctor 2.0.10) [https://asciidoctor.org]
Runtime Environment (node v14.0.0 on darwin)
CLI version 3.2.0
````

**Comment by Mogztter** [comment]
I think we should probably open an issue upstream: https://gitlab.pagedmedia.org/tools/pagedjs
Ideally, if you could produce a "simple" HTML page and replace the inline Paged.js script by the following that would be awesome:

```
<script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
```

For instance, you can take a look at the `test.html` I've recently submitted: https://gitlab.pagedmedia.org/tools/pagedjs/issues/215

**Comment by henriette-einstein** [comment]
I have created a test document named "test.html" which includes the polyfill as you suggested. In this scenario, the page is generated and it does not have any errors when opened in Chrome. The file is included in the pull-request.

However, the numbering is still incorrect and the settings for margin-inside and margin-outside (which are needed if you want facing-pages) are not evaluated.

So basically I think, we have an error in paged.js and another one in asciidoctor-web-pdf.

**Comment by Mogztter** [comment]
> I have created a test document named "test.html" which includes the polyfill as you suggested. In this scenario, the page is generated and it does not have any errors when opened in Chrome. The file is included in the pull-request.

The polyfill is using the latest version available of Paged.js.
I've released a new version of Asciidoctor Web PDF based on Paged.js v0.1.41. So you in theory the error should also be gone in Asciidoctor Web PDF 1.0.0-apha.8.

> So basically I think, we have an error in paged.js and another one in asciidoctor-web-pdf.

I don't think we have an issue in asciidoctor-web-pdf but you are free to prove me wrong 😄 
Please test with the latest version of Asciidoctor Web PDF and let me know if you still have an exception.

> BTW: Paged.js must have some means of figuring out the correct page number. If you look at the the source of the document in Chrome, you can see that the content-divs have an attribute "data-page-number" that contains the correct page number.
> However, the numbering is still incorrect and the settings for margin-inside and margin-outside (which are needed if you want facing-pages) are not evaluated.

Is it possible to create a minimal example to reproduce the numbering issue and another one to reproduce the margin-inside/margin-outside issue?
I'm currently working on a few fixes for Paged.js that might be related.

**Comment by henriette-einstein** [comment]
Now I cannot generate a PDF at all.

````

arpablo@Big-Henni asciidoctor-web-pdf % asciidoctor-pdf examples/document/document.adoc 
Unable to generate the PDF - Error: Error: Failed to launch the browser process! spawn /usr/local/lib/node_modules/asciidoctor-pdf/node_modules/puppeteer/.local-chromium/mac-756035/chrome-mac/Chromium.app/Contents/MacOS/Chromium ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

````

I am using the following asciidoctor-web-pdf version

````
arpablo@Big-Henni asciidoctor-web-pdf % asciidoctor-pdf --version
Asciidoctor PDF 1.0.0-alpha.8 using Asciidoctor.js 2.2.0 (Asciidoctor 2.0.10) [https://asciidoctor.org]
Runtime Environment (node v14.0.0 on darwin)
CLI version 3.4.0
````

cleaned the complete installation with

````
 rm -rf /usr/local/lib/node_modules/asciidoctor-pdf
````
but still get the same result.

I am running on a standard iMac

<img width="303" alt="Bildschirmfoto 2020-06-15 um 10 11 30" src="https://user-images.githubusercontent.com/45788168/84633442-af05d300-aef0-11ea-8bc6-3f26ee2dbe3f.png">

Changing node to the latest lts version also resulted in the same error.

**Comment by henriette-einstein** [comment]
I don't know whether that is of any relevance, but I have installed the latest Chrome version on this machine.

<img width="452" alt="Bildschirmfoto 2020-06-15 um 10 18 00" src="https://user-images.githubusercontent.com/45788168/84634104-9f3abe80-aef1-11ea-80ae-11fe0101d144.png">

**Comment by Mogztter** [comment]
I cannot reproduce on my mac:

```console
$ npm i --save-dev asciidoctor-pdf @asciidoctor/core
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> puppeteer@3.3.0 install /Users/guillaumegrossetie/dev/temp/node_modules/puppeteer
> node install.js

Downloading Chromium r756035 - 124.1 Mb [====================] 100% 0.0s
Chromium (756035) downloaded to /Users/guillaumegrossetie/dev/temp/node_modules/puppeteer/.local-chromium/mac-756035

> core-js@2.6.11 postinstall /Users/guillaumegrossetie/dev/temp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.

+ asciidoctor-pdf@1.0.0-alpha.8
+ @asciidoctor/core@2.2.0
added 130 packages from 184 contributors and audited 130 packages in 36.378s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ asciidoctor-pdf test.adoc
````

```console
$ node -v
v12.18.0
```

I'm using macOS Catalina v10.15.3.

> I don't know whether that is of any relevance, but I have installed the latest Chrome version on this machine.

No, Puppeteer is using a specific version, downloaded and installed in `/usr/local/lib/node_modules/asciidoctor-pdf/node_modules/puppeteer/.local-chromium/mac-756035/chrome-mac/Chromium.app/Contents/MacOS/Chromium`.

Can you try to install locally and not globally and/or use `nvm` to install on your user space (i.e. in `/Users/xxx` and not in `/usr/local/lib`).
The EONENT error might indicate a permission issue. Did you get an error/warning during the installation?

**Comment by henriette-einstein** [comment]
Sorry! The problem was that I installed the last version with `yarn global add asciidoctor-pdf` and the latest version with `npm i -g asciidoctor-pdf`. And the yarn global directory was in the path before the npm global directory...

I was using yarn, because vue uses yarn as it's default package manager.
Now I have uninstalled yarn completely and will always use npm instead.

**Comment by henriette-einstein** [comment]
I cannot reproduce the issue with the latest version of asciidoctor-pdf. The issue can be closed. I will create two new issues with isolated testcases for the mentioned paged.js problems.

**Comment by Mogztter** [comment]
No worries!

> I will create two new issues with isolated testcases for the mentioned paged.js problems.

Thanks :+1:
