### ISSUE TITLE
`source-highlighter` not working

### ISSUE THREAD

**Issue by abelsromero** [Mogztter/asciidoctor-web-pdf#288]
I tried a simple example with highlightjs and prettify and none worked. Looked through the repo and examples and I saw nothing related.
Is it supported?

**Comment by Mogztter** [comment]
Hey @abelsromero, it should be supported (at least for Highlight.js).
I will investigate 👀

**Comment by Mogztter** [comment]
@abelsromero Did you check https://github.com/Mogztter/asciidoctor-web-pdf/blob/master/examples/document/basic-example.pdf? Could you share a sample document that reproduce this issue?

**Comment by Mogztter** [comment]
Nice catch, it's a regression introduced in https://github.com/Mogztter/asciidoctor-web-pdf/commit/7397e3613a39576b166556c2a0245ae558c2b6c4.

Asciidoctor only assigns the syntax highlighter on the Document when the basebackend is `html`: https://github.com/asciidoctor/asciidoctor/blob/4284a176fac29bdde62288f13e7ebb18defeb9aa/lib/asciidoctor/document.rb#L1208-L1218

As you can see, we are currently using `html5`... I will fix this issue and add a test to make sure that we won't break it again.

**Comment by Mogztter** [comment]
@mojavelinux we might want to revisit this condition `if (basebackend = attrs['basebackend']) == 'html'` now that we have a proper API for syntax highlighter?
It seems a bit restrictive to set the `syntax_highlighter` attribute only when the `basebackend` is `html` no?

**Comment by mojavelinux** [comment]
This is actually correct. The syntax highlighters assume they are producing HTML, so the basebackend must be html (which indicates the backend knows how to deal with HTML fragments).

**Comment by mojavelinux** [comment]
The basebackend is not meant to be versioned, so it should be `html`.

**Comment by Mogztter** [comment]
> This is actually correct. The syntax highlighters assume they are producing HTML, so the basebackend must be html (which indicates the backend knows how to deal with HTML fragments).

Got it.

> The basebackend is not meant to be versioned, so it should be html.

👍🏻

**Comment by abelsromero** [comment]
@Mogztter thanks a lot! For what it's worth, I tested with the HEAD version and it's working now :+1:

**Comment by Mogztter** [comment]
Thanks for the validation.
I will probably release a new version soon since it's a pretty big regression 😬

**Comment by Mogztter** [comment]
I just released https://github.com/Mogztter/asciidoctor-web-pdf/releases/tag/v1.0.0-alpha.9
