### ISSUE TITLE
ToC on left: bad rendering

### ISSUE THREAD

**Issue by gquintana** [Mogztter/asciidoctor-web-pdf#307]
When a document is using
```
:toc: left
```
The table of contents is rendered in the background

See attached sample and result
[test.zip](https://github.com/Mogztter/asciidoctor-web-pdf/files/5179893/test.zip)

```
  "@asciidoctor/core": "^2.2.0",
  "asciidoctor-pdf": "^1.0.0-alpha.9",
```

**Comment by Mogztter** [comment]
When using `:toc: left` or `:toc: right` the Table Of Contents should be "off-canvas" (outside of the page).
So we can either remove it or ignore the value and put the Table Of Contents in the preamble.

Here's what Asciidoctor PDF (Ruby) produces:

![expected](https://user-images.githubusercontent.com/333276/92366904-0b465080-f0f6-11ea-90af-907bf60943f4.png)


Is that what you had in mind? Did you expect this result?

**Comment by gquintana** [comment]
Yes. It's my current work workaround replace `:toc: left` by `toc`.

I ignore how PDF rendering magic is happening, but I noticed the HTML produced by asciidoctor-pdf is also broken compared to the one produced by asciidoctor core
[test-html.zip](https://github.com/Mogztter/asciidoctor-web-pdf/files/5186343/test-html.zip)
Said differently, the PDF produced by manually printing to PDF int the browser the HTML generated by asciidoctor core is  better with respect to ToC positionning.

Thansk for you help ;-)
