### ISSUE TITLE
When ToC is enabled, lists are not rendered

### ISSUE THREAD

**Issue by gquintana** [Mogztter/asciidoctor-web-pdf#349]
When a doc contains both `:toc:`  and a list (number or bullet), the list is not properly rendered.
See attached example.
Removing the toc is a workaround.

[lists.zip](https://github.com/Mogztter/asciidoctor-web-pdf/files/5506649/lists.zip)

**Comment by Mogztter** [comment]
Thanks for the attached example, I was able to quickly reproduce this issue :+1: 
The root cause was that the Table Of Contents list items style was incorrectly applied to other list items :grimacing:

**Comment by DanielSWolf** [comment]
@Mogztter Do you plan to publish a new version in the near future? It would be great if I could use the fixed version.

**Comment by Mogztter** [comment]
@DanielSWolf Yes, that's on my to-do list :wink:

**Comment by Mogztter** [comment]
https://github.com/Mogztter/asciidoctor-web-pdf/releases/tag/v1.0.0-alpha.11 is out! :tada: 

@DanielSWolf Let me know if everything is working on your end.

**Comment by DanielSWolf** [comment]
I just tried the new version. For me, all kinds of lists now render as expected in the presence of a table of contents. Thank you!
