### ISSUE TITLE
How to define page's header and footer?

### ISSUE THREAD

**Issue by edl7878** [Mogztter/asciidoctor-web-pdf#351]
How to define page's header and footer?

**Comment by Mogztter** [comment]
Someone already asked more or less the same question: https://github.com/Mogztter/asciidoctor-web-pdf/issues/312#issuecomment-691069186

And, as mentioned in my comment, if it's working fine, we should definitely document this feature.

**Comment by edl7878** [comment]
Got it, thanks.
