### ISSUE TITLE
How do I create a custom layout with multiple authors?

### ISSUE THREAD

**Issue by helo9** [Mogztter/asciidoctor-web-pdf#357]
Looking at https://asciidoctor.github.io/asciidoctor.js/2.0.3/#documentauthor I do not understand how to handle multiple authors. Is is though possible in custom layouts?

**Comment by Mogztter** [comment]
Hello @helo9,

Yes, you can use `Document.getAuthors` function to retrieve the authors (an `Array` of `Author`) from a document: https://asciidoctor.github.io/asciidoctor.js/2.0.3/#documentgetauthors

**Comment by helo9** [comment]
Thank you @Mogztter!

I was not yet able to get this running, using this snippet inside my template.
```
tmp = ""
for (const author of node.getDocument().getAuthors()) {
    if (tmp != "") {
      tmp.concat(",")
    }
    tmp.concat(author.getName())
  }
```
Do you see my mistake here. Otherwise I will upload a complete example tomorrow.

**Comment by Mogztter** [comment]
What is `node`? Are you sure that `node` is not a `Document`?

```js
module.exports = {
  document: (node) => {
    for (const author of node.getAuthors()) {
      // ...
    }
  }
}
```

**Comment by helo9** [comment]
Thank you @Mogztter!

I was not yet able to get this running, using this snippet inside my template.
```
tmp = ""
for (const author of node.getDocument().getAuthors()) {
    if (tmp != "") {
      tmp.concat(",")
    }
    tmp.concat(author.getName())
  }
```
Do you see my mistake here. Otherwise I will upload a complete example. 

By the way, I am only allowed to close the issue with this comment.

**Comment by Mogztter** [comment]
@helo9 working? not working? :wink:

**Comment by helo9** [comment]
Sorry, I accidentially closed the issue, although I was not able getting it to work and had no time yet to prepare a minimal example. At latest tomorrow I will have time for that!

**Comment by helo9** [comment]
Checked it with a minimal example and it is working now.
`node` was the `Document` in my case, but an additional `getDocument` call seems to be no problem.

Thanks a lot!

**Comment by Mogztter** [comment]
Awesome, thanks for the follow-up :+1:
