### ISSUE TITLE
Increase page margins

### ISSUE THREAD

**Issue by DanielSWolf** [Mogztter/asciidoctor-web-pdf#359]
When I create a PDF file using Asciidoctor Web PDF, it has nice side margins (the borders on the left and right side). The top and bottom margins, however, are very slim, almost non-existent.

To reproduce:

1. Take [this minimal AsciiDoc file](https://github.com/Mogztter/asciidoctor-web-pdf/files/5623276/lorem.adoc.zip)

2. Call `asciidoctor-web-pdf --out-file lorem.pdf lorem.adoc`

3. This is [the resulting PDF file](https://github.com/Mogztter/asciidoctor-web-pdf/files/5623228/lorem.pdf). Note that on the very first page, the top margin still looks good. On the following pages, however, both top and bottom margin are only a few millimetres wide.

Is it possible to increase these margins?

More generally, is there a way to specify the page margins when calling `asciidoctor-web-pdf`?

**Comment by Mogztter** [comment]
Hey @DanielSWolf 

Yes, you can configure margin using CSS:

```css
@page {
  margin: 3cm 2cm 3cm 2cm;
}
```

Please read the "Custom styles" section to find out how to provide a custom stylesheet: https://github.com/Mogztter/asciidoctor-web-pdf#configuration

However, the top margin is indeed very slim:

| Asciidoctor PDF | Asciidoctor Web PDF |
| -- | -- |
| ![asciidoctor-pdf-top-margin](https://user-images.githubusercontent.com/333276/100760735-5ec4f380-33f2-11eb-9e6c-55144559432a.png) | ![asciidoctor-web-pdf-top-margin](https://user-images.githubusercontent.com/333276/100760738-5ff62080-33f2-11eb-94a5-48a44e96027f.png)
| ![asciidoctor-pdf-top-margin-first-page](https://user-images.githubusercontent.com/333276/100760742-5ff62080-33f2-11eb-8704-b153fc1b7f11.png) | ![asciidoctor-web-pdf-top-margin-first-page](https://user-images.githubusercontent.com/333276/100760740-5ff62080-33f2-11eb-8ad4-6ae6633c8086.png)

I'm willing to update the default style to increase the margin a bit to match Asciidoctor PDF current output.

**Comment by DanielSWolf** [comment]
I just tried version 1.0.0-alpha.11. The new default margins look much better to me. Thank you!
