### ISSUE TITLE
Accessible PDFs are not possible given the current setup

### ISSUE THREAD

**Issue by webpigeon** [Mogztter/asciidoctor-web-pdf#410]
Recent versions of chrome can generate tagged PDFs, but at present, there are two issues that prevent tagged PDF outputs from `asciidoctor-web-pdf`. Both of these are addressable (so with code changes this tool can generate tagged PDFs today) but as these require removing a feature I wanted to post this as an issue rather than do a PR for the changes.

## puppeteer does not pass `--export-tagged-pdf` to the generator
There is an outstanding pull request for dealing with this, but it's not been merged. https://github.com/puppeteer/puppeteer/pull/5337

This can be fixed by passing the argument when creating the browser in `_launch` in `lib/browser.js`:

```
args: ['--no-sandbox', '--allow-file-access-from-files', '--export-tagged-pdf']
```

That's the easy one :D. The problem is, that even though the PDF generated is now tagged, the PDF output by web-pdf isn't. The reason for this is because of a workaround for another issue.

## PDF-lib does not support tagged PDFs
There is a work-around for the lack of outline support in the PDFs in `lib/converter.js`. This workaround involves taking the (tagged) pdf from chrome and running through `pdf-lib`. During my testing, it looks like this step strips the tagging from the PDF when it's re-saved.

There is an open issue for this against pdf-lib but it's pretty much a non-starter by the looks of it. https://github.com/Hopding/pdf-lib/issues/756

Commenting out these lines:

```
      //let pdfDoc = await PDFDocument.load(pdf)
      //pdfDoc = await addOutline(pdfDoc, doc)
      //pdfDoc = await addMetadata(pdfDoc, doc)
      //pdf = await pdfDoc.save()
```

Results in the chrome PDF being used, but then the issue mentioned in the comment is present, which removes a feature from the tool. I've checked and the bug report against chromium still seems to be open.

I'm not sure what the correct course of action is in this case. It seems that the tool can either support accessible pdfs (which are required by my institution for my worksheets) or can support outlines.

**Comment by Mogztter** [comment]
Thanks for the detailed explanation.
I had no idea that it was possible to add PDF tags to improve accessibility, that's great!

> PDF-lib does not support tagged PDFs

pdf-lib does a great job and the maintainer is always supportive so I would recommend to provide simple reproduction cases.
Realistically, we will still need pdf-lib for post-processing for quite some time. I'm not even sure that Chromium will ever implement all the existing features that we have today.

So I think this is the best way forward as it would benefit all pdf-lib users.

> This can be fixed by passing the argument when creating the browser in _launch in lib/browser.js:

I don't min adding this argument ahead of time, if it does not have any side-effects on older versions of Chromium (i.e., versions that don't support this feature).

> I'm not sure what the correct course of action is in this case. It seems that the tool can either support accessible pdfs (which are required by my institution for my worksheets) or can support outlines.

A short-term solution could be to add an option/attribute to disable post-processing (outline + metadata) but I don't know if it's a good idea...
Could you please provide a sample document so I can play with a tagged PDF?

Thanks!

**Comment by webpigeon** [comment]
Here is a sample document, both produced from the same asciidoc source (one with the changes to produce a tagged pdf and the other one without). 

The main way I know they are not tagged is because of the accessibility plugin my workplace uses for Moodle. When uploading the tagged version it goes from 11% compliance to something like 97%. It's not happy about the lack of metadata, but as you say the best way to get that sorted is to fix it via pdf-lib.

> I don't min adding this argument ahead of time, if it does not have any side-effects on older versions of Chromium (i.e., versions that don't support this feature).
I've not tried with other versions of chromium, but the one that was downloaded by NPM when I built asciidoc to test seemed to work. The flag has been supported since mid-2020 ish (Internet seems to think it was added in Chrome 85) https://9to5google.com/2020/07/29/chrome-tagged-pdf/. 

> pdf-lib does a great job and the maintainer is always supportive so I would recommend providing simple reproduction cases.

I know it's fairly challenging to support tagged PDFs (almost no FOSS PDF library I've looked at does it!). It's come up before against the `asciidoctor-pdf` project which rely on prawn (which doesn't support tagged PDFs). There are LaTeX packages which do a reasonably good job of it and my institution has a working LaTeX template which injects tags in the correct places. I use for most of my other PDFs (assignments and slides), but (to me at least) asciidoc makes more sense for guides/tutorials.

> A short-term solution could be to add an option/attribute to disable post-processing (outline + metadata) but I don't know if it's a good idea...

That could work :+1: 

## Untagged PDF (default)
![untagged_pdf_example](https://user-images.githubusercontent.com/525964/108191689-58016f00-710b-11eb-868c-9d8140af2612.jpg)

[vr220_gettingstarted_notagged.pdf](https://github.com/Mogztter/asciidoctor-web-pdf/files/5994960/vr220_gettingstarted_notagged.pdf)

## Tagged PDF (modified)
![tagged_pdf_example](https://user-images.githubusercontent.com/525964/108191712-5fc11380-710b-11eb-9788-5c019736aa3b.jpg)

[vr220_gettingstarted_tagged.pdf](https://github.com/Mogztter/asciidoctor-web-pdf/files/5994961/vr220_gettingstarted_tagged.pdf)

**Comment by Mogztter** [comment]
Thanks again for providing for such detailed information!
I have a good news, this is what I get on master branch (using the latest version of `pdf-lib` 1.16.0):


```console
$ ./bin/asciidoctor-web-pdf test.adoc && pdfinfo test.pdf
Title:          Hello World
Subject:        
Keywords:       
Author:         
Creator:        Asciidoctor Web PDF 1.0.0-alpha.11
Producer:       Asciidoctor Web PDF 1.0.0-alpha.11
CreationDate:   Wed Feb 17 22:13:45 2021 CET
ModDate:        Wed Feb 17 22:04:09 2021 CET
Tagged:         yes
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      594.96 x 841.92 pts (A4)
Page rot:       0
File size:      1442501 bytes
Optimized:      no
PDF version:    1.7
```

As you can see `Tagged:         yes` :tada: 

> This can be fixed by passing the argument when creating the browser in _launch in lib/browser.js:

If you want to submit a pull request, I will gladly merge it, otherwise I will do this change in the next few days :+1:

**Comment by webpigeon** [comment]
It's done at PR https://github.com/Mogztter/asciidoctor-web-pdf/pull/416 :)

**Comment by Mogztter** [comment]
For reference, here's the Chrome Tagged PDF Export Design Doc: https://docs.google.com/document/d/1ku6QNtAHEqVnRGqFzpmlMe1fowkjCX9miHj8Kx1cFlk/edit

They recommend to use [QPDF](http://qpdf.sourceforge.net/) to debug PDF document:

```console
# Convert a PDF file to a QDF file, a special text-only,
# more human-readable format.
qpdf --qdf hello.pdf hello.qdf
```
```console
# Edit hello.qdf with a text editor (avoid emacs, it
# messes up qdf files). Make changes to the file
# just like you were editing any other source code.
vim hello.qdf
```
```console
# Fix the QDF file, doing things like recomputing
# cross-references and eliminating inconsistencies.
fix-qdf < hello.qdf > hello2.qdf
```
```console
# Convert the edited QDF file back to a valid PDF file.
qpdf hello2.qdf hello2.pdf
```

The regression metrics section is also interesting:

> Since we’re adding a feature that will enhance the PDFs we’re exporting, we expect this to have a cost, so the goal is to keep it reasonable, not eliminate that cost. Here are the things we plan to track:
>- The size of the resulting PDF file (we expect it to grow, but by a modest amount like 10%)
>- The time it takes to generate the PDF file (should increase, but not more than 20%).
>- The temporary RAM used when exporting a PDF (should increase, but not more than 20%).
>- Crash / failure rates (should not go up at all).

In other words, enabling this feature will have a cost but I think we should produce accessible PDFs by default. If the induced performance cost is unacceptable for some users, then we could provide an option to disable it. But I strongly believe it should be enabled by default.

**Comment by webpigeon** [comment]
That's awesome! thanks for finding that. I use qpdf as part of my workflow for the LaTeX documents (to linearize them).
