### ISSUE TITLE
Create a proper Asciidoctor converter with two phases

### ISSUE THREAD

**Issue by Mogztter** [Mogztter/asciidoctor-web-pdf#44]
The first phase should create an HTML page and the second phase should convert the HTML page to PDF using Puppeteer.

Inspiration: https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/converter.rb

**Comment by Mogztter** [comment]
It won't be easy because Puppeteer is asynchronous but the Asciidoctor converter mechanism is synchronous.
So when Asciidoctor converts a document, it expects to get a synchronous response from the converter.

**Comment by oncletom** [comment]
I suspected it would be hackish to do that in JavaScript but it appears that a C++ module does block the thread while an async function awaits to be resolved: https://www.npmjs.com/package/deasync

**Comment by Mogztter** [comment]
The AsciiDoc to HTML phase is now declared as an Asciidoctor converter.
I don't think that including the HTML to PDF phase in the converter brings much value.

I'm closing this issue for now, but we can reevaluate later.
