### ISSUE TITLE
Add a root-folder in distribution bundles (zip files)

### ISSUE THREAD

**Issue by wh81752** [Mogztter/asciidoctor-web-pdf#456]
Unzipping a precompiled binaries messes up the current folder with all kind of (installation) clutter. Better to have a root-folder like `asciidoctor-web-pdf-x.y.z` that contains everyhing.

**Comment by Mogztter** [comment]
I don't have a strong opinion on this one. Usually, I'm using `unzip file.zip -d some-dir` but I guess it can be useful if you are using "Extract in this directory".

Again, feel free to adjust the release process to put everything into a directory before zipping.
