### ISSUE TITLE
Missing list marker at page breaks (in specific situations)

### ISSUE THREAD

**Issue by rillbert** [Mogztter/asciidoctor-web-pdf#473]
Hi,

The list marker of the first item that appear on a new page does not seem to be treated correctly
when the list is included via a master document. This seem to affect both ordered and unordered
lists.

In some scenarios, it disappears completely and in other the marker is shown last on the previous
page but the list item text is shown on the new page. The effect seems to be connected to when the
vertical alignment happens to introduce a page brake. In some cases it works as expected.

I'm attaching a zip with adoc sources that replicate this bug when using the default stylesheets.

I'm also attaching the pdf's separately, one that expose the bug (generated by asciidoctor-web-pdf) and one showing the expected behaviour (generated with 'standard' asciidoctor-pdf)
[bugreport.zip](https://github.com/Mogztter/asciidoctor-web-pdf/files/6409121/bugreport.zip)
[buggy_list.pdf](https://github.com/Mogztter/asciidoctor-web-pdf/files/6409122/buggy_list.pdf)
[ok_list_with_asciidoc_pdf.pdf](https://github.com/Mogztter/asciidoctor-web-pdf/files/6409123/ok_list_with_asciidoc_pdf.pdf)

**Comment by Mogztter** [comment]
Hi @rillbert,

Thanks for providing a reproduction case.
I think it's the same issue (briefly) described here: https://github.com/Mogztter/asciidoctor-web-pdf/issues/377

I would like to keep only one issue, could you please move your comment in #377 so I can close this issue?
Thanks!

**Comment by rillbert** [comment]
Sure, I was a bit pressed for time so I missed the already existing issue.
I've now copied the comment and the files there.

**Comment by Mogztter** [comment]
No worries

> I've now copied the comment and the files there.

Thanks 👍🏻
