### ISSUE TITLE
PR lost from master to main

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-web-pdf#519]
I saw this was renamed from `master` to `main` and was hunting for my PR. It was not in the commit history...

Only via email I found this:

![image](https://user-images.githubusercontent.com/674783/120603270-effb4c80-c49f-11eb-918b-9ec8a0ca637c.png)

Did something get chomped by the change process?

**Comment by danyill** [comment]
The lost commit appears to be bea670f

**Comment by danyill** [comment]
No I think it's there all along in #513. My bad :cry:

**Comment by Mogztter** [comment]
No worries 😉
