### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by matklad** [Mogztter/asciidoctor-web-pdf#52]
Given that the project is now named Asciidoctor.js PDF, perhaps we should rename the repo? 

Context: I am writing that promised blog post right now, and I want to name the project correctly.
By the way, here's the repository with slides: https://github.com/matklad/rust-course

**Comment by Mogztter** [comment]
> Given that the project is now named Asciidoctor.js PDF, perhaps we should rename the repo?

You mean rename the repository to `asciidoctor.js-pdf` ? I don't like when the `.js` is not at the end  but it's just a personal taste.
So if we agree that it's more logical/consistent then we should do it.

**Comment by matklad** [comment]
>You mean rename the repository to asciidoctor.js-pdf

Yeah, it is confusing if the repo and the project are named differently. I don't have a strong opinion here, if you like current repository name more, there's no reason to change it :)

**Comment by Mogztter** [comment]
Closing as the repository was renamed to `asciidoctor-web-pdf`.

We intend to rename the binary from `asciidoctor-pdf` to `asciidoctor-web-pdf` (and maybe the npm package as well).

See: https://github.com/Mogztter/asciidoctor-web-pdf/issues/286
