### ISSUE TITLE
[question] Move repo to https://github.com/asciidoctor?

### ISSUE THREAD

**Issue by abelsromero** [Mogztter/asciidoctor-web-pdf#53]
Just curios why this project is not in the organization

**Comment by Mogztter** [comment]
I think the main reason is that this project is in experimental state but we could as long as we mention that in the README (to avoid confusion).

We did made some good progress to provide an out-of-the-box PDF output (to mimic `asciidoctor-pdf`) but they are still some unsupported features (most notably footer notes).

**Comment by Mogztter** [comment]
Closing as I think I've answered your question?
