### ISSUE TITLE
Bug in setting puppeteer timeouts

### ISSUE THREAD

**Issue by siaccarino** [Mogztter/asciidoctor-web-pdf#633]
The pull request #236 did not change the puppeteer rendering timeout - it changes the time asciidoc-web-pdf waits for puppeteer.

According to [puppeteer pdf options](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagepdfoptions) a timeout shall be passed to the page.pdf() call instead.

Rendering of complex documents on slow machines could easily exceed the 30s limit and no matter what I configure for the rendering timeout, puppeteer always throws a timeout exception after 30s.

I created a fix #632 for this issue

**Comment by Mogztter** [comment]
This is closely related to https://github.com/Mogztter/asciidoctor-web-pdf/issues/612

**Comment by siaccarino** [comment]
30 second is not much - lets assume the conversion is running on a busy jenkins agent in a CI chain and you have a lot of pages with tables, source code examples ...

**Comment by siaccarino** [comment]
I'll update my PR according to your suggestion
