### ISSUE TITLE
PDF output is unreliable

### ISSUE THREAD

**Issue by siaccarino** [Mogztter/asciidoctor-web-pdf#635]
I get a warning "Unable to find destination...." for a chapter that definitely don't contain umlauts.

The adoc contains:
```
=== Communication strategy

blah...

=== Problem analysis

blah...

=== Alert notification strategy
```

The outline dictionary generated in https://github.com/Mogztter/asciidoctor-web-pdf/blob/3e1bb2ecf1b781f06bf555556b0935496283ac15/lib/outline.js#L76 looks like

```
PDFName { encodedName: '/communication_strategy' } => PDFArray { array: [Array], context: [PDFContext] },
PDFName { encodedName: '/_alert_notification_strategy' } => PDFArray { array: [Array], context: [PDFContext] },
```

The HTML looks like:
```
<li class="toc-entry"><a href="#communication_strategy">5.3. Communication strategy</a></li>
<li class="toc-entry"><a href="#problem_analysis">5.4. Problem analysis</a></li>
<li class="toc-entry"><a href="#_alert_notification_strategy">5.5. Alert notification strategy</a></li>
```

After PDF inspection it looks like the PDF file generated by puppeteer is wrong
Analysis finished: it's Paged.js which messes up the PDF output - it generates a page break right after the communication_strategy header, the following paragraph is vanished from DOM:

PDF copy & paste
5.3. Communication strategy
------ Page 12 of 18
5.4. Problem analysis

blah...

**Comment by Mogztter** [comment]
The umlaut error message should be removed and replaced, see: https://github.com/Mogztter/asciidoctor-web-pdf/issues/267#issuecomment-980544430
It might be possible to intercept the message `Unable to layout item: ...` sent by Paged.js but that would probably be more brittle.

**Comment by siaccarino** [comment]
Debug analysis shows that root cause of lost content is 100% pagejs - the lost content is still in DOM but it is invisible. I'll fill bug report there.

There is not much asciidoc-web-pdf can do here but to write a warning:

- PDF output for complex documents needs to be reviewed, especially if there are warnings like "Unable..." during the build
- Keep an eye on limitations enforced by pagination of big elements like tables, code examples, images

**Comment by siaccarino** [comment]
![hiddenparagraph](https://user-images.githubusercontent.com/28953627/158139716-7da64d6f-1645-4d95-a42b-c73414b5a50d.png)
Content is not vanished but hidden

**Comment by siaccarino** [comment]
"Unable to layout item" seems to be the best solution to me
